analyze_requirements_task:
  description: >
    Analyze the following user requirements for prompt engineering solution:
    
    Primary Goal: {task_description}
    Task Type: {task_type}
    Model Preference: {model_preference}
    Tone: {tone}
    Context: {context}
    Sample Data: {data_input}
    Few-Shot Examples: {examples}

    Review the user preferences and identify:
    1. Key requirements and constraints
    2. Critical success factors
    3. Potential challenges and risks
    4. Available resources and limitations
    5. Technical and business context

    Provide a detailed analysis in JSON format covering all aspects mentioned above.
  expected_output: >
    A comprehensive JSON analysis containing summary, constraints, success factors, risks, and context information.
  agent: architect

develop_strategies_task:
  description: >
    Based on the requirements analysis, develop three distinct strategic approaches for the prompt engineering solution.
    Each strategy should optimize for different priorities while ensuring the core requirements are met.

    User Requirements:
    Task Description: {task_description}
    Task Type: {task_type}
    Model Preference: {model_preference}
    Tone: {tone}
    Context: {context}
    Sample Data: {data_input}
    
    Consider the following optimization directions:
    - Accuracy (result reliability)
    - Efficiency (processing speed)
    - Cost (resource utilization)
    - Maintainability (ease of updates)
    - Robustness (error handling)
    - Consistency (output stability)
    - Scalability (handling different scales)
    - Security (data protection)
    - Flexibility (adaptation capability)
    - Explainability (result traceability)

    Develop THREE complete strategies, each focusing on different priorities.
    Make sure each strategy is fully detailed and actionable.
    Provide the output in JSON format with detailed implementation steps for each strategy.
  expected_output: >
    A JSON object containing three detailed strategic approaches, each with implementation steps, benefits, trade-offs, and success metrics.
  agent: architect
  context: [analyze_requirements_task]
