optimize_prompt_direction:
  description: >
    Architect's Analysis for Direction:
    {direction}

    Based on the above analysis from the architect, create a complete prompt structure that implements this optimization direction.
    
    User Requirements:
    Task Description: {task_description}
    Task Type: {task_type}
    Model Preference: {model_preference}
    Tone: {tone}
    Context: {context}
    Sample Data: {data_input}
    Few-Shot Examples: {examples}

    Your task is to generate a complete prompt structure following these components:
    // ... existing code ...
  expected_output: >
    A JSON object containing the complete prompt structure, selected methods with justification, explanation, and guidelines.
  agent: prompt_engineer 