analyze_requirements_task:
  description: >
    Analyze the following user requirements for prompt engineering solution:
    
    Primary Goal: {task_description}
    Task Type: {task_type}
    Model Preference: {model_preference}
    Tone: {tone}
    Context: {context}
    Sample Data: {data_input}
    Few-Shot Examples: {examples}

    Review the user preferences and identify THREE most relevant and helpful optimization directions.
    For each direction, provide:
    1. Clear description of the optimization focus
    2. Why this direction is particularly relevant to the user's needs
    3. Expected benefits and improvements
    4. Key considerations for implementation

    Provide the output in JSON format with three distinct optimization directions.
  expected_output: >
    A JSON object containing three optimization directions, each with focus, relevance, benefits, and implementation considerations.
  agent: architect 